matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 5.0.100-preview.3.20216.6
      install:
        - dotnet restore
      script:    
        - dotnet test exchange.test/exchange.test.csproj