dist: xenial
os: linux
jobs:
  include:
    - language: csharp
      addons:
        snaps:
        - name: dotnet-sdk
          classic: true
          channel: 5.0/beta
      mono: none
      script:
        - sudo snap alias dotnet-sdk.dotnet dotnet
        - dotnet --version
        - dotnet restore exchange.test/exchange.test.csproj
        - dotnet test exchange.test/exchange.test.csproj

    - language: node_js
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      node_js:
        - 10
        - 9
        - 8
        - node
      script:
        - npm install
        - npm test