dist: xenial
os: linux
language: csharp
jobs:
  include:
    - language: csharp
      addons:
        snaps:
        - name: dotnet-sdk
          classic: true
          channel: 5.0/beta
      mono: none
      script:
        - sudo snap alias dotnet-sdk.dotnet dotnet
        - dotnet --version
        - dotnet restore exchange.test/exchange.test.csproj
        - dotnet test exchange.test/exchange.test.csproj

    - language: node_js
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_script:
        - sudo apt-get update
        - sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        - sudo apt-get install default-jdk 
        - sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
        - sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
        - sudo apt-get -y update
        - sudo apt-get -y install google-chrome-stable
        - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo mv chromedriver /usr/bin/chromedriver
        - sudo chown root:root /usr/bin/chromedriver
        - sudo chmod +x /usr/bin/chromedriver
        - wget https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar
        - wget http://www.java2s.com/Code/JarDownload/testng/testng-6.8.7.jar.zip
        - unzip testng-6.8.7.jar.zip
        - cd exchange.signalR.client.web.frontend
      node_js:
        - 10
        - 9
        - 8
        - node
      script:
        - npm install
        - npm test
        - npm run e2e