dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: 5.0/beta
sudo: required
language: csharp
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - dotnet restore exchange.test/exchange.test.csproj
  - dotnet test exchange.test/exchange.test.csproj
