matrix:
   include:
     - language: csharp
       mono: none
       install:
         - dotnet restore exchange.test/exchange.test.csproj
       script:
         - dotnet test exchange.test/exchange.test.csproj
