version: "3.7"
            
services:
    #main exchange service
    exchange.service:
        container_name: exchange.service
        build: .
        ports:
            - 5000:5000
            - 5001:5001