version: "3.7"

volumes:
    mongo_db:
        name: mongo_db
        driver: local
        driver_opts:
            device: 'D:\Docker\data\db'
            o: 'bind'
            type: 'none'
    mongo_configdb:
        name: mongo_configdb
        driver: local
        driver_opts:
            device: 'D:\Docker\data\configdb'
            o: 'bind'
            type: 'none'
            
services:
    #mongo Database
    exchange.mongodb:
        image: mongo:${MONGO_DB_VERSION}
        container_name: mongodb
        # List directories to mount
        volumes:
            - mongo_db:/data/db:rw
            - mongo_configdb:/data/configdb:rw
            - ./mongodb/init.sh:/init.sh:rw
            - ./mongodb/mongo-users-init.js:/docker-entrypoint-initdb.d/mongo-users-init.js:ro
        command: [
            "./init.sh"
        ]
        ports:
            - 27017-27019:27017-27019

    #celery
    celery:
        container_name: celery
        # All files and folders in the currect directory
        build: .
        # List directories to mount
        volumes:
            - .:/usr/src/app
        command: celery -A app.tasks.task_work:celery worker --loglevel=info -P eventlet
        depends_on:
            - exchange.mongodb

    #machine learning web application
    exchange.service.mi.service:
        container_name: machineLearningService
        build: .    
        volumes:
            - .:/usr/src/app
        # Application will run on port 5005
        # Access to directory has to be shared
        ports:
            - 5005:5005
        command: python3.6 main.py
        depends_on:
            - exchange.mongodb
